name:                Query-Lang-Interpreter
version:             0.1.0.0
github:              "githubuser/Query-Lang-Interpreter"
license:             GNU
author:              "Christopher Lawrence"
maintainer:          "cl5g19@soton.ac.uk"
copyright:           "2021 Christopher Lawrence"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kit-Law/Query-Lang-Interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- array
- split

library:
  source-dirs: src

executables:
  csvql:
    main:                csvql.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Query-Lang-Interpreter
    - split

tests:
  Query-Lang-Interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Query-Lang-Interpreter
